---
title: "Pepperwood-Microclimate"
author: "Aji John"
date: "12/21/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
```

## R Markdown



```{r}
pws <-read.csv("https://raw.githubusercontent.com/CelesteDodge/PepperwoodVegPlots/master/HOBO/PPW_HOBO_2013_Master.csv")

```

## Check the imported columns

You can also embed plots, for example:

```{echo=FALSE}
str(pws)
head(pws)
pws$tsfmt<- as.POSIXct(pws$Date.Time,format="%Y-%m-%d %H:%M:%S")
head(pws)

```

Lets try to do the summary by site, day for the 2013 data for RH and Temperature

```{echo=FALSE}
head(pws %>%mutate(HR= format(tsfmt,"%H"),DATE=format(tsfmt,"%Y-%m-%d")) %>% group_by(Plot,DATE,HR) %>% summarise(minHrlyTemp = min(Temp),maxHrlyTemp = max(Temp),minHrlyRH = min(RH),maxHrlyRH = max(RH)) %>% as.data.frame())

```

Lets write to CSV

```{echo=FALSE}

pws %>%mutate(HR= format(tsfmt,"%H"),DATE=format(tsfmt,"%Y-%m-%d")) %>% group_by(Plot,DATE,HR) %>% summarise(minHrlyTemp = min(Temp),maxHrlyTemp = max(Temp),minHrlyRH = min(RH),maxHrlyRH = max(RH)) %>% as.data.frame() %>% write.csv("Hobo-2013-Summary-Hourly.csv")

```

Now, lets create the daily file. We can follow the same, but now summarize by DATE
